### PR TITLE
remove spaces in urlParts

### PR DESCRIPTION
**Pull request by razanbilwani**

### CODE REVIEW

**Comment by razanbilwani** [comment]
@shidhincr Or, I could add trim, wdyt?

**Comment by shidhincr** [comment]
@razanbilwani Good to use `trim`

**Comment by shidhincr** [comment]
@razanbilwani Better to do like this

In https://github.com/namshi/roger/blob/master/src/client/components/projectDetails.jsx#L33

```js
let [repo, branch] = ( path || '' ).split(':').map(item => item.trim());
```

**Comment by razanbilwani** [comment]
@shidhincr cool, did it in #38

**Pull request closed without merging**
